// Write a java program to store details of customer ,
//  customer id , customer name , customer address
// 1. create Customer class with attribute  
// customerId of int type , customerName of type String ,
//  customerAddress of type String
// 2. Note that customerId should be autogenerated starting from 1.
// 3. add get/set method  constructor 
// 4. create  CustomerTest class with main method and
//  create object of customer add the details and print customer
//   name
// by calling   getCustomerName() method of customer calss


// Customer.java

public class Customer {
  // Declare instance variables
  int customerId;
  String customerName;
  String customerAddress;

  // Create a static variable to track the next customer ID
  private static int nextCustomerId = 1;

  // Constructor to initialize the customer's details
  public Customer(String customerName, String customerAddress) {
    // Assign a unique customer ID
    this.customerId = nextCustomerId;
    nextCustomerId++;

    // Initialize the customer's name and address
    this.customerName = customerName;
    this.customerAddress = customerAddress;
  }

  public Customer(int i, String string, String string2) {
}

// Getter and setter methods for customer's name and address
  public String getCustomerName() {
    return this.customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public String getCustomerAddress() {
    return this.customerAddress;
  }

  public void setCustomerAddress(String customerAddress) {
    this.customerAddress = customerAddress;
  }
}

// CustomerTest.java

 class CustomerTest {
  public static void main(String[] args) {
    // Create a new customer with the name and address
    Customer customer = new Customer("chandrashekhar", "23 birlasoft Hinjawadi pune");

    // Print the customer's name
    System.out.println(customer.getCustomerName());
  }
}
